import '../styles/globals.css'

import type { Metadata } from 'next'
import Script from 'next/script'

import { GoogleSans } from '@/styles/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const scripts = [
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/jMeb.min.js?t_1748',
  // 'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/jquery-3.7.0.min.js?t_1748',
  // 'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/jquery-migrate-3.4.0.min.js?t_1748',
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/cookies.min.js?t_1748',
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/TextDecoder.min.js?t_1748',
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/meb-jslib/MebUtil.min.js?t_1748',
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/meb-jslib/MebUtil.MebZip.min.js?t_1748',
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/meb-jslib/vendor/jszip.min.js?t_1748',
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/meb-jslib/MebUtil.MebCrypto.min.js?1',
  'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/meb-jslib/MebUtil.ContentTransformer.min.js?t_1748',
  // 'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/sweetalert-for-ie.min.js?t_1748',
  // 'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/sweetalert2-ie9.min.js?t_1748',
  // 'https://1146890965.rsc.cdn77.org/web/newux/dist/assets/js/jquery.matchHeight.min.js?t_1748',
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body className={`${GoogleSans.variable} antialiased`}>{children}</body>
      {scripts.map((script, index) => (
        <Script key={`script-${index}`} src={script} strategy="afterInteractive" />
      ))}
    </html>
  )
}
